version: '3.8'
services:
  django:
    build: ./django_files
    container_name: django
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    command: sh -c "python manage.py migrate --run-syncdb  && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_files/:/app/
    ports:
      - 8000:8000
    env_file:
      - ".env"  # whenever run .env must be where compose.yml file located.
#
#  pgdb:
#    image: postgres
#    container_name: pgdb
#    restart: always
#    ports:
#      - "5431:5432"
#    env_file:
#      - ".env"
#    volumes:
#      - ${PWD}/mydb/_data/postgres:/var/lib/postgresql/data #'mydb' folder created in base directory with all adding data.
#      # this volume mounted keep all data as backup.

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis