# Generated by Django 4.1.4 on 2023-01-02 05:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('establish', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('hq_state', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(blank=True, max_length=500, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('is_activated', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_mail_verified', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='users.myusers')),
            ],
        ),
    ]
