# Generated by Django 4.1.4 on 2023-01-20 09:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='product_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('color', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('fashion', 'fashion'), ('grocery', 'grocery'), ('beauty', 'beauty'), ('appliance', 'appliance')], default='beauty', max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('availability', models.BooleanField(choices=[(1, 'instore'), (0, 'out_of_stock')])),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('incart', 'incart'), ('order-placed', 'order-placed'), ('cancelled', 'cancelled')], default='incart', max_length=120)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
