# Generated by Django 4.1.4 on 2023-01-07 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'seller'), (2, 'buyer')], null=True)),
                ('password', models.CharField(max_length=300)),
                ('profile_logo', models.ImageField(blank=True, null=True, upload_to='customer_image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])])),
                ('building_name', models.CharField(max_length=500, null=True)),
                ('lane1', models.CharField(max_length=500, null=True)),
                ('lane2', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('pin', models.PositiveIntegerField(null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('seller_name', models.CharField(blank=True, max_length=150, null=True)),
                ('seller_reg', models.CharField(blank=True, max_length=500, null=True)),
                ('founded', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('Not Say', 'Not Say')], default='Not Say', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
